# shellcheck shell=bash
# Optional: bond the two Intel I226-V 2.5 GbE ports (igc driver) with netplan.

network_detect_ports() {
  local n drv ports=()
  for n in /sys/class/net/*; do
    [[ -e $n/device/driver ]] || continue
    drv=$(basename "$(readlink -f "$n/device/driver")")
    [[ $drv == igc ]] && ports+=("$(basename "$n")")
  done
  echo "${ports[*]}"
}

stage_network() {
  if [[ $BOND_ENABLE != 1 ]]; then
    log "BOND_ENABLE=0: leaving networking as installed"
    return 0
  fi

  local -a ports
  read -r -a ports <<<"${BOND_INTERFACES:-$(network_detect_ports)}"
  ((${#ports[@]} == 2)) || die "expected 2 I226-V (igc) ports, found: ${ports[*]:-none}; set BOND_INTERFACES"
  case $BOND_MODE in 802.3ad | active-backup | balance-alb) ;; *) die "unsupported BOND_MODE=$BOND_MODE" ;; esac

  local renderer=networkd
  systemctl is-active --quiet NetworkManager 2>/dev/null && renderer=NetworkManager

  local params addr p dns_list=""
  if [[ $BOND_MODE == 802.3ad ]]; then
    params='        mode: 802.3ad
        lacp-rate: fast
        mii-monitor-interval: 100
        transmit-hash-policy: layer3+4'
  else
    params="        mode: $BOND_MODE
        mii-monitor-interval: 100
        primary: ${ports[0]}"
  fi
  if [[ -n $BOND_ADDRESS ]]; then
    [[ -n $BOND_GATEWAY ]] || die "BOND_ADDRESS set without BOND_GATEWAY"
    for p in $BOND_DNS; do dns_list+="${dns_list:+, }$p"; done
    addr="      dhcp4: false
      addresses: [$BOND_ADDRESS]
      routes:
        - to: default
          via: $BOND_GATEWAY
      nameservers:
        addresses: [$dns_list]"
  else
    addr="      dhcp4: true"
  fi

  # Later netplan files override earlier ones key by key, so switching the ports'
  # own dhcp off here wins over 50-cloud-init.yaml without editing it.
  write_file /etc/netplan/60-ailab-bond.yaml 0600 <<EOF
# ailab: ${ports[*]} bonded as bond0 ($BOND_MODE). Generated by install.sh.
network:
  version: 2
  renderer: $renderer
  ethernets:
    ${ports[0]}:
      dhcp4: false
      dhcp6: false
      optional: true
    ${ports[1]}:
      dhcp4: false
      dhcp6: false
      optional: true
  bonds:
    bond0:
      interfaces: [${ports[0]}, ${ports[1]}]
      parameters:
$params
$addr
EOF

  # Stop cloud-init from regenerating the network config on the next boot.
  if [[ -d /etc/cloud/cloud.cfg.d ]]; then
    write_file /etc/cloud/cloud.cfg.d/99-ailab-disable-network-config.cfg <<'EOF'
network: {config: disabled}
EOF
  fi

  run netplan generate
  if [[ $BOND_APPLY == 1 ]]; then
    warn "applying the bond now - SSH sessions on ${ports[*]} may drop and the IP may change"
    run netplan apply
    ok "bond0 applied"
  else
    log "bond0 written to /etc/netplan/60-ailab-bond.yaml but not applied."
    log "From the local console run:  sudo netplan try   (reverts after 120 s unless confirmed)"
  fi
  [[ $BOND_MODE == 802.3ad ]] && log "802.3ad needs both switch ports in one LACP group"
  return 0
}
